services:
  DailyhotApi:
    build:
      context: .
      target: runner
    ports:
      - "6688:6688"
    volumes:
      - "./logs:/app/logs"
    networks:
      - app-network
    environment:
      - PORT=6688
    user: "114514"
    restart: always

networks:
  app-network:
    name: app-network
    external: true
